### ISSUE TITLE
Deployment failed! on latest wildfly server

### ISSUE THREAD

**Issue by lkhatkar** [mechero/spring-boot-jboss-wildfly#4]
Please see attached log file

[log.txt](https://github.com/mechero/spring-boot-jboss-wildfly/files/5964994/log.txt)

**Comment by mechero** [comment]
I would need more info to figure out what is exactly your problem... Did you use the same repository / Wildfly server versions? etc.

**Comment by lkhatkar** [comment]
Downgraded Wildfly server and it worked. Thank you.
